# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 12:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mezzanine.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0004_auto_20161128_2147'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.Page')),
                ('content', mezzanine.core.fields.RichTextField(verbose_name='Content')),
                ('content_en', mezzanine.core.fields.RichTextField(null=True, verbose_name='Content')),
                ('content_ru', mezzanine.core.fields.RichTextField(null=True, verbose_name='Content')),
            ],
            options={
                'verbose_name_plural': 'Custom pages',
                'ordering': ('_order',),
                'verbose_name': 'Custom page',
            },
            bases=('pages.page', models.Model),
        ),
    ]
