# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_portfoliopost_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliopost',
            name='rating_average',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='portfoliopost',
            name='rating_count',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='portfoliopost',
            name='rating_sum',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='portfoliopost',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='portfolioposts', to='portfolio.PortfolioCategory', verbose_name='Categories'),
        ),
    ]
